services:
  postgres:
    image: postgres:15
    container_name: tracker-postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tracker_db
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: .
    container_name: tracker-backend
    ports:
      - "9090:8080"
    environment:
      # Важно: стучимся к базе по имени контейнера "postgres"
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/tracker_db
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  pgdata: